erDiagram

    %% Relationships
    
    fact_registerenhetsrettsandel_encrypted ||--|| dim_registerenhetsrettsandel_encrypted : registerenhetsrettsandelId
    fact_registerenhetsrettsandel_encrypted }o--|| dim_fysisk_person_encrypted : zk_rettighetshaver_personId
    fact_registerenhetsrettsandel_encrypted }o--|| dim_juridisk_person : zk_rettighetshaver_personId
    fact_registerenhetsrettsandel_encrypted }|--|| dim_registerenhet : zk_realkobletTil_registerenhetId
    fact_registerenhetsrettsandel_encrypted }|--|| dim_registerenhetsrett : zk_registerenhetsrettId

    dim_registerenhetsrett ||--|| fact_registerenhet : zk_registerenhetId
    dim_registerenhetsrett ||--|| dim_registerenhetsrettstypekode : zk_registerenhetsrettstypekodeId
    
    fact_registerenhet ||--|| dim_registerenhet : registerenhetId
    fact_registerenhet }|--|| dim_borettslag : zk_borettslag_id
    fact_registerenhet }|--|| dim_kommune : zk_kommuneId
    fact_registerenhet ||--o| fact_registerenhet : zk_omnummererttil_registerenhetId
    fact_registerenhet }o--|| dim_adresse_encrypted : zk_adresseId

    dim_borettslag }o--o| dim_juridisk_person : zk_personId
    dim_borettslag }o--o| dim_fysisk_person_encrypted : zk_personId

    fact_rettsstiftelse ||--|| dim_rettsstiftelse : rettsstiftelseId
    fact_rettsstiftelse ||--|| dim_dokument : zk_dokumentId
    fact_rettsstiftelse ||--|| dim_omsetning_encrypted : zk_omsetningId
    fact_rettsstiftelse ||--|| dim_aarsaksparagrafkode : zk_aarsaksparagrafkodeid
    fact_rettsstiftelse ||--|| dim_aarsaksgebyrfritakkode : zk_aarsaksgebyrfritakkodeid
    fact_rettsstiftelse ||--|| dim_periodekode : zk_periodekodeid
    fact_rettsstiftelse ||--|| dim_anketypekode : zk_anketypekodeid

    dim_rettsstiftelse_til_dokument }o--|| fact_rettsstiftelse : zk_rettsstiftelseId
    dim_rettsstiftelse_til_dokument }o--o| dim_dokument : zk_dokumentId
    dim_rettsstiftelse_til_person_encrypted }o--|| fact_rettsstiftelse : zk_rettsstiftelseId
    dim_rettsstiftelse_til_person_encrypted }o--o| dim_fysisk_person_encrypted : zk_personId
    dim_rettsstiftelse_til_person_encrypted }o--o| dim_juridisk_person : zk_personId
    dim_rettsstiftelse_til_registerenhetsrett_encrypted }o--|| fact_rettsstiftelse : zk_rettsstiftelseId
    dim_rettsstiftelse_til_registerenhetsrett_encrypted }o--o| dim_registerenhetsrett : zk_registerenhetsrettId
    dim_rettsstiftelse_til_rettsstiftelse }o--|| fact_rettsstiftelse : zk_kilde_rettsstiftelseId
    dim_rettsstiftelse_til_rettsstiftelse }o--|| fact_rettsstiftelse : zk_maal_rettsstiftelseId

    fact_rettsstiftelse_beloep }o--|| fact_rettsstiftelse : zk_rettsstiftelseId
    fact_rettsstiftelse_beloep }|--|| dim_valutakodekode : zk_valutakodekodeId
    fact_rettsstiftelse_beloepforperiode }o--|| fact_rettsstiftelse : zk_rettsstiftelseId
    fact_rettsstiftelse_beloepforperiode }|--|| dim_valutakodekode : zk_valutakodekodeId

    dim_delavrett ||--|| fact_rettsstiftelse : zk_kilde_rettsstiftelse
    dim_delavrett ||--|| fact_rettsstiftelse : zk_maal_rettsstiftelse

    dim_delavrett_til_registerenhetsrett_encrypted }o--|| dim_delavrett : zk_delavrettId
    dim_delavrett_til_registerenhetsrett_encrypted }o--o| dim_registerenhetsrett : zk_registerenhetsrettId
    dim_delavrett_til_registerenhetsrettsandel_encrypted }o--|| dim_delavrett : zk_delavrettId
    dim_delavrett_til_registerenhetsrettsandel_encrypted }o--o| fact_registerenhetsrettsandel_encrypted : zk_registerenhetsrettsandelId

    fact_hefte_i_registerenhetsrettsandel_encrypted }o--|| dim_registerenhetsrettsandel_encrypted : zk_registerenhetsrettsandelId
    fact_hefte_i_registerenhetsrettsandel_encrypted }o--|| dim_rettsstiftelse : zk_rettsstiftelseId

    fact_overfoering_encrypted }o--|| dim_rettsstiftelse : zk_overfoert_rettstiftelseId
    fact_overfoering_encrypted }o--o| dim_rettsstiftelse : zk_overfoerende_rettstiftelseId

    dim_overfoering_omfatter_encrypted }|--|| fact_overfoering_encrypted : zk_overfoeringId

    dim_overfoering_omfatter_encrypted }o--o| dim_registerenhetsrett : zk_fra_registerenhetsrettId
    dim_overfoering_omfatter_encrypted }o--o| dim_registerenhetsrett : zk_til_registerenhetsrettid
    dim_overfoering_omfatter_encrypted }o--o| dim_registerenhetsrettsandel_encrypted : zk_fra_registerenhetsrettsandelId
    dim_overfoering_omfatter_encrypted }o--o| dim_registerenhetsrettsandel_encrypted : zk_til_registerenhetsrettsandelid

    fact_dokument ||--|| dim_dokument : dokumentId
    fact_dokument |o--o| fact_dokument : zk_omdokulerttil_dokumentId
    fact_dokument }o--o| dim_saksinformasjon : zk_saksinformasjonId
    fact_dokument }|--|| dim_embetekode : zk_embetekodeId
    fact_dokument }|--|| dim_dokumentstatuskode : zk_dokumentstatusKodeId
    fact_dokument }|--|| dim_valutakodekode : zk_valutakodeKodeId

    dim_saksinformasjon }|--|| dim_saksinformasjon_behandlingsutfallkode : zk_saksinformasjonBehandlingsutfallKodeId
    dim_saksinformasjon }|--|| dim_saksinformasjon_saksstatuskode : zk_saksinformasjonSaksstatusKodeId
    
    dim_saksperson_encrypted ||--|| dim_saksinformasjon : zk_saksinformasjonId
    dim_saksperson_encrypted }|--|| dim_identifikasjonsnummertypekode : zk_identifikasjonsnummertypeKodeId

    fact_omsetning_encrypted ||--|| dim_omsetning_encrypted : omsetningId
    fact_omsetning_encrypted }|--|| dim_omsetningstypekode : zk_omsetningstypeKodeId
    fact_omsetning_encrypted }|--|| dim_dokumentavgiftsaarsakkode : zk_dokumentavgiftsaarsakKodeId

    fact_omsetning_beloep_encrypted }|--|| dim_omsetning_encrypted : zk_omsetningId
    fact_omsetning_beloep_encrypted }|--|| dim_valutakodekode : zk_valutakodekodeId

    dim_omsattregisterenhetsrett_encrypted }|--|| fact_omsetning_encrypted : zk_omsetningId
    dim_omsattregisterenhetsrett_encrypted }o--|| dim_registerenhetsrett : zk_registerenhetsrettId
    dim_omsattregisterenhetsrett_encrypted }|--|| dim_boligtypekode : zk_boligtypeKodeId
    dim_omsattregisterenhetsrett_encrypted }|--|| dim_brukstypekode : zk_brukstypeKodeId

    dim_omsattregisterenhetsrettsandel_encrypted }o--|| dim_omsattregisterenhetsrett_encrypted : zk_omsattregisterenhetsrettId
    dim_omsattregisterenhetsrettsandel_encrypted }o--o| fact_registerenhetsrettsandel_encrypted : zk_registerenhetsrettsandelId

    dim_fysisk_person_encrypted }|--|| dim_identifikasjonsnummertypekode : zk_identifikasjonsnummertypekodeId
    dim_juridisk_person }|--|| dim_identifikasjonsnummertypekode : zk_identifikasjonsnummertypekodeId

    dim_adresse_encrypted }|--|| dim_landkodekode : zk_landkodekodeid
    dim_adresse_encrypted }|--|| dim_kommune : zk_kommuneid
    dim_adresse_encrypted }|--o| matrikkel_dim_adresse : zk_matrikkel_adresseId
    dim_adresse_encrypted }|--o| matrikkel_dim_bruksenheter : zk_matrikkel_bruksenhetId


    %% REGISTERENHET, RETT OG RETTSANDEL

    fact_registerenhetsrettsandel_encrypted {
        int registerenhetsrettsandelId PK

        int zk_registerenhetsrettId FK "FK to dim_registerenhetsrett"
        int zk_rettighetshaver_personId FK "FK to dim_juridisk_person / dim_fysisk_person_encrypted"
        int zk_realkobletTil_registerenhetId FK "FK to dim_registerenhet"
        
        int teller "Numerator of the share"
        int nevner "Denominator of the share"

        int keyId "FK to encryption key table"
        timestamp oppdateringsdato "Date updated"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_registerenhetsrettsandel_encrypted {
        int registerenhetsrettsandelId PK

        int lopenummer "Serial number"
        boolean historisk "Historical flag"

        int keyId "FK to encryption key table"
        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    fact_registerenhet {
        int registerenhetId FK

        int zk_kommuneId FK "FK to dim_kommune"
        int zk_borettslagId FK "FK to dim_borettslag (nullable)"
        int zk_adresseId FK "FK to dim_adresse_encrypted"
        int zk_omnummererttil_registerenhetId FK "FK to fact_registerenhet (self-referencing)"

        timestamp oppdateringsdato "Date updated"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_registerenhet {
        int registerenhetId PK

        string registerenhetKategori "Class"
        boolean utgaatt "Expired flag"

        int gaardsnummer "Farm number"
        int bruksnummer "Usage number"
        int festenummer "Lease number"
        int seksjonsnummer "Section number"
        int andelsnummer "Share number"
        boolean tinglyst
        boolean beregneterseksjonert
        boolean beregnetharaktivefestegrunner
        boolean jordsameie

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_registerenhetsrett {
        int registerenhetsrettId PK

        int zk_registerenhetId FK "FK to fact_registerenhet"
        int zk_registerenhetsrettstypeKodeId "FK to dim_registerenhetsrettstypekode"

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_borettslag {
        int borettslagId PK
        int zk_personId FK "FK to dim_juridisk_person / dim_fysisk_person_encrypted"

        boolean historisk "Historical flag"

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_kommune {
        int kommuneId PK

        string kommunenummer "Municipality number"
        string navn "Municipality name"
        boolean historisk "Municipality historical flag"

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    
    %% RETTSSTIFTELSE

    fact_rettsstiftelse {
        int rettsstiftelseId "PK"

        int zk_dokumentId "FK to dim_dokument"
        int zk_omsetningId "FK to dim_omsetning_encrypted"

        int zk_rettsstiftelsestypekodeId FK
        int zk_periodekodeId FK
        int zk_aarsaksparagrafKodeId FK
        int zk_aarsaksgebyrfritakKodeId FK
        int zk_oppr_rettsstiftelsestypekodeId FK
        int zk_anketypekodeId FK

        int leietid
        int festetid_antall_aar

        timestamp leiefradato
        timestamp oversendtlagmannsretten
        timestamp nektet
        timestamp festefradato
        timestamp notifikasjonsdato
        timestamp dato_for_avgj_anken_gjelder
        timestamp paaberopt_prioritet_fra
        timestamp fristforendeligregistrering
        
        date avholdt_dato
        string avholdt_klokkeslett

        timestamp oppdateringsdato
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_rettsstiftelse {
        int rettsstiftelseId "PK"

        string rettsstiftelseKategori "Class"
        int rettsstiftelsesnummer

        boolean hargebyr
        string saksnummer
        string tingrett
        boolean verdiendring
        string prioritet
        string navn
        boolean foreloepig
        string identifikator_nve
        boolean historisk

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_delavrett {
        int delavrettId "PK"

        int zk_kilde_rettsstiftelse "FK to fact_rettsstiftelse"
        int zk_maal_rettsstiftelse "FK to fact_rettsstiftelse"

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_delavrett_til_registerenhetsrett_encrypted {
        int delavrettTilRegisterenhetsrettId "PK"

        int zk_delavrettId "FK to dim_delavrett"
        int zk_registerenhetsrettId "FK to dim_registerenhetsrett"

        int keyId "FK to encryption key table"
        timestamp oppdateringsdato
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_delavrett_til_registerenhetsrettsandel_encrypted {
        int delavrettTilRegisterenhetsrettsandelId "PK"

        int zk_delavrettId "FK to dim_delavrett"
        int zk_registerenhetsrettsandelId "FK to fact_registerenhetsrettsandel_encrypted"

        int keyId "FK to encryption key table"
        timestamp oppdateringsdato
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_rettsstiftelse_til_dokument {
        int rettsstiftelsetildokumentId "PK"

        int zk_rettsstiftelseId "FK to fact_rettsstiftelse"
        int zk_dokumentId "FK to dim_dokument"

        timestamp oppdateringsdato
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_rettsstiftelse_til_person_encrypted {
        int rettsstiftelsetilpersonId "PK"

        string rettsstiftelsetilpersonKategori

        int zk_rettsstiftelseId "FK to fact_rettsstiftelse"
        int zk_personId "FK to dim_fysisk_person_encrypted / dim_juridisk_person"

        int keyId "FK to encryption key table"
        timestamp oppdateringsdato
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_rettsstiftelse_til_registerenhetsrett_encrypted {
        int rettsstiftelsetilregisterenhetsrettId "PK"

        string rettsstiftelsetilregisterenhetsrettKategori

        int zk_rettsstiftelseId "FK to fact_rettsstiftelse"
        int zk_registerenhetsrettId "FK to dim_registerenhetsrett"

        int keyId "FK to encryption key table"
        timestamp oppdateringsdato
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_rettsstiftelse_til_rettsstiftelse {
        int rettsstiftelsetilrettsstiftelseId "PK"

        string rettsstiftelsetilrettsstiftelseKategori

        int zk_kilde_rettsstiftelseId "FK to fact_rettsstiftelse"
        int zk_maal_rettsstiftelseId "FK to fact_rettsstiftelse"

        timestamp oppdateringsdato
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    fact_rettsstiftelse_beloep {
        int rettsstiftelseBeloepId PK

        int zk_rettsstiftelseId "FK to fact_rettsstiftelse"
        int zk_valutakodekodeId "FK to dim_valutakodekode"

        string rettsstiftelseBeloepKategori

        int beloepsverdi "Amount value"
        string beloepstekst "Amount text"
        
        timestamp oppdateringsdato "Date updated"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    fact_rettsstiftelse_beloepforperiode {
        int rettsstiftelseBeloepforperiodeId PK

        int zk_rettsstiftelseId "FK to fact_rettsstiftelse"
        int zk_valutakodekodeId "FK to dim_valutakodekode"
        int zk_periodekodeId "FK to dim_periodekode"

        string rettsstiftelseBeloepforperiodeKategori

        int beloepsverdi "Amount value"
        string beloepstekst "Amount text"
        
        timestamp oppdateringsdato "Date updated"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    fact_hefte_i_registerenhetsrettsandel_encrypted {
        int hefteIRegisterenhetsrettsandelId PK

        int zk_registerenhetsrettsandelId "FK to dim_registerenhetsrettsandel_encrypted"
        int zk_rettsstiftelseId "FK to dim_rettsstiftelse"

        boolean historisk "Historical flag"

        int teller
        int nevner

        int keyId "FK to encryption key table"
        timestamp oppdateringsdato "Date updated"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    %% OVERFØRING

    fact_overfoering_encrypted {
        int overfoeringId PK

        int zk_overfoert_rettstiftelseId FK "FK to dim_rettsstiftelse"
        int zk_overfoerende_rettstiftelseId FK "FK to dim_rettsstiftelse"
        
        int keyId "FK to encryption key table"
        timestamp oppdateringsdato "Date updated"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_overfoering_omfatter_encrypted {
        int overfoeringOmfatterId PK

        int zk_overfoeringId FK "FK to fact_overfoering_encrypted"
        int zk_fra_registerenhetsrettId FK "FK to dim_registerenhetsrett"
        int zk_til_registerenhetsrettId FK "FK to dim_registerenhetsrett"
        int zk_fra_registerenhetsrettsandelId FK "FK to fact_registerenhetsrettsandel_encrypted"
        int zk_til_registerenhetsrettsandelId FK "FK to fact_registerenhetsrettsandel_encrypted"

        int keyId "FK to encryption key table"
        timestamp oppdateringsdato
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }


    %% OMSETNING

    fact_omsetning_encrypted {
        int omsetningId PK

        int zk_omsetningstypeKodeId FK "FK to dim_omsetningstypeKode"
        int zk_dokumentavgiftsaarsakKodeId FK "FK to dim_dokumentavgiftsaarsakKode"

        int keyId "FK to encryption key table"
        timestamp oppdateringsdato "Date updated"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_omsetning_encrypted {
        int omsetningId PK
        
        string omsetningKategori "Class"

        boolean utlysttilsalgpaadetfriemarked
        boolean hardokumentavgift

        int keyId "FK to encryption key table"
        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    fact_omsetning_beloep_encrypted {
        int omsetningBeloepId PK

        int zk_omsetningId FK "FK to dim_omsetning_encrypted"
        int zk_valutakodekodeId "FK to dim_valutakodekode"

        string omsetningBeloepKategori "Rolle"

        int beloepsverdi "Amount value"
        string beloepstekst "Amount text"
        
        int keyId "FK to encryption key table"
        timestamp oppdateringsdato "Date updated"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_omsattregisterenhetsrett_encrypted {
        int omsattRegisterenhetsrettId PK

        %% Fra ownerid:
        int zk_omsetningId FK "FK to fact_omsetning_encrypted"

        int zk_registerenhetsrettId FK "FK to dim_registerenhetsrett"
        int zk_boligtypekodeid
        int zk_brukstypekodeid

        %% Fra 'Class':
        string omsattRegisterenhetsrettKategori

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }
    
    dim_omsattregisterenhetsrettsandel_encrypted {
        int omsattRegisterenhetsrettsandelId "PK"
        
        %% Fra 'rolle':
        string omsattRegisterenhetsrettsandelKategori
        
        int zk_omsattregisterenhetsrettId "FK to dim_omsattregisterenhetsrett_encrypted"
        int zk_registerenhetsrettsandelId "FK to fact_registerenhetsrettsandel_encrypted"
        
        string keyId FK "FK to encryption key table"
        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    %% DOKUMENT

    fact_dokument {
        int dokumentId FK

        int zk_saksinformasjonId FK "FK to dim_saksinformasjon"
        int zk_omdokulerttil_dokumentId FK "FK to fact_dokument (self-referencing)"

        int zk_embetekodeId FK "FK to dim_embetekode"
        int zk_dokumentstatusKodeId FK "FK to dim_dokumentstatuskode"
        int zk_valutakodeKodeId FK "FK to dim_valutakodekode"

        int gebyrbeloepsverdi
        string gebyrbeloepstekst
        timestamp registreringstidspunkt

        timestamp oppdateringsdato "Date updated"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_dokument {
        int dokumentId PK

        int dokumentaar
        int dokumentnummer
        boolean datoregistrert
        boolean historisk

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }


    %% PERSON

    dim_fysisk_person_encrypted {
        int fysiskPersonId PK

        int zk_identifikasjonsnummerTypeKodeId FK
        string identifikasjonsnummer "Identification number"
        string navn

        boolean historisk "Historical flag"
        timestamp oppdateringsdato "Date updated"

        string keyId FK "FK to encryption key table"
        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_juridisk_person {
        int juridiskPersonId PK

        int zk_identifikasjonsnummerTypeKodeId FK
        string identifikasjonsnummer "Identification number"
        string navn
        
        boolean historisk "Historical flag"
        timestamp oppdateringsdato "Date updated"

        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }


    dim_adresse_encrypted {
        int adresseId
        
        int zk_landkodekodeid FK "FK to dim_landkodekode"
        int zk_kommuneid FK "FK to dim_kommune"
        int zk_matrikkel_adresseId FK "FK to adresse in matrikkel"
        int zk_matrikkel_bruksenhetId FK "FK to bruksenhet in matrikkel"

        string adresseKategori "Class"

        int bolignummer
        string adressekode
        string adressenavn
        int husnummer
        string bokstav
        int gaardsnummer
        int bruksnummer
        int festenummer
        int undernummer
        string adressetekst

        int keyId "FK to encryption key table"
        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_saksinformasjon {
        int saksinformasjonId "PK"

        int saksnummer
        date mottaksdato
        date foelgebrevsdato

        int zk_saksinformasjonSaksstatusKodeId "FK to dim_saksinformasjonSaksstatusKode"
        int zk_saksinformasjonBehandlingsutfallKodeId "FK to dim_saksinformasjonBehandlingsutfallKode"

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_saksperson_encrypted {
        %% SakspersonId opprettet som en hash av of saksinformasjonId + rolle:
        int sakspersonId PK "Surrogate key"

        int zk_saksinformasjonId FK "FK to dim_saksinformasjon"
        int zk_identifikasjonsnummerTypeKodeId "FK to dim_identifikasjonsnummertypekode"
        
        int identifikasjonsnummer "Identification number"
        string sakspersonrolle "Rolle (innsender, fakturamottaker, mottaker)"

        string adresselinje1
        string adresselinje2
        string adresselinje3
        string epostadresse
        string referanse
        string postnummer
        string poststed
        string land

        int keyId "FK to encryption key table"
        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }


    %% KODELISTER

    dim_aarsaksgebyrfritakkode {
        int aarsaksgebyrfritakkodeid "PK"
        string aarsaksgebyrfritak

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_aarsaksparagrafkode {
        int aarsaksparagrafkodeid "PK"
        string aarsaksparagraf

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_anketypekode {
        int anketypekodeid "PK"
        string anketype

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_boligtypekode {
        int boligtypekodeid "PK"
        string boligtype

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_brukstypekode {
        int brukstypekodeid "PK"
        string brukstype

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_dokumentavgiftsaarsakkode {
        int dokumentavgiftsaarsakkodeid "PK"
        string dokumentavgiftsaarsak

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_dokumentstatuskode {
        int dokumentstatuskodeid "PK"
        string dokumentstatus

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_embetekode {
        int embetekodeid "PK"
        string embete

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_identifikasjonsnummertypekode {
        int identifikasjonsnummertypekodeid "PK"
        string identifikasjonsnummertype

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_landkodekode {
        int landkodekodeid "PK"
        string landkode

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_omsetningstypekode {
        int omsetningstypekodeid "PK"
        string omsetningstype

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_periodekode {
        int periodekodeid "PK"
        string periode

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_registerenhetsrettstypekode {
        int registerenhetsrettstypekodeId "PK"
        string registerenhetsrettstypekode

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_saksinformasjon_behandlingsutfallkode {
        int saksinformasjonBehandlingsutfallKodeId "PK"
        string saksinformasjonBehandlingsutfall

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_saksinformasjon_saksstatuskode {
        int saksinformasjonsaksstatuskodeId "PK"
        string saksinformasjonsaksstatus

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

    dim_valutakodekode {
        int valutakodekodeid "PK"
        string valutakode

        timestamp oppdateringsdato "Date updated"
        timestamp from_datetime "Start of SCD2-validity for this record"
        timestamp to_datetime "End of SCD2-validity for this record"
        timestamp zx_ingest_timestamp "Timestamp for data ingest"
    }

