erDiagram

    fact_eierforhold ||--|| dim_matrikkelenhet: "zk_matrikkelenhetId/zk_eiendeMatrikkelenhetId"


    dim_matrikkelenhet ||--|| fact_matrikkelenhet: matrikkelenhetId

    fact_eierforhold ||--|| dim_juridisk_person: zk_eierId
    fact_eierforhold ||--|| dim_fysisk_person: zk_eierId
    fact_eierforhold ||--|| dim_annen_person: zk_eierId
    fact_matrikkelenhet ||--|| dim_juridisk_person: zk_eiendeMatrikkelenhetId

    fact_matrikkelenhet ||--|| dim_kommuner_matrikkel: zk_kommuneId

    dim_kommuner_grunnbok ||--|| dim_registerenhet: "zk_kommuneId"
    dim_matrikkelenhet ||--|| dim_kommuner_matrikkel: "zk_kommuneId"
    dim_kommuner_grunnbok ||--|| dim_kommuner_matrikkel: "kommunenummer"
    dim_matrikkelenhet ||--|| dim_registerenhet: "gaardsnummer, festenummer, seksjonsnummer, bruksnummer"


%%    fact_bygning ||--|| dim_juridisk_person: kontaktpersoner
%%    fact_bygning ||--|| dim_fysisk_person: kontaktpersoner
%%    fact_bygning ||--|| dim_annen_person: kontaktpersoner
%%    fact_bruksenheter ||--|| dim_juridisk_person: zk_kostraVirksomhetId


    %%%%%%%%%%%% Faktatabeller %%%%%%%%%%%%

    fact_eierforhold{
        bigint eierforholdId PK
        bigint zk_matrikkelenhetId FK
        bigint zk_eiendeMatrikkelenhetId FK
        bigint zk_eierId FK
        bigint zk_eierforholdKodeId FK
        bigint zk_kommuneId FK
    }

    fact_matrikkelenhet{
        bigint matrikkelenhetId PK
        bigint zk_historiskArealkildeId FK
        bigint zk_kommuneId FK
        array zk_teigerForMatrikkelenhet FK
    }

%%    fact_bygning {
%%        bigint bygningId PK
%%        array kontaktpersoner
%%        bigint zk_avlopsKodeId FK
%%        array zk_bruksenhetIds FK
%%        bigint zk_bygningsstatusKodeId FK
%%        bigint zk_bygningstypeKodeId FK
%%    }

%%    fact_bruksenheter {
%%        bigint bruksenhetId PK
%%        bigint zk_adresseId FK
%%        bigint zk_bruksenhetstypeKodeId FK
%%        bigint zk_bygningId FK
%%        bigint zk_kostraVirksomhetId FK
%%        bigint zk_matrikkelenhetId FK
%%    }

    %%%%%%%%%%%% Dimensjonstabeller %%%%%%%%%%%%

    dim_matrikkelenhet{
        bigint matrikkelenhetId PK
        bigint gaardsnummer
        bigint bruksnummer
        bigint festenummer
        bigint seksjonsnummer
        bigint zk_kommuneId
    }

   dim_kommuner_matrikkel{
        bigint kommuneId PK
        string kommunenummer
    }

    dim_kommuner_grunnbok{
        bigint kommuneId PK
        string kommunenummer
    }

    %% Juridisk person er tegnet opp med forenklede kolonnenavn
    dim_juridisk_person{
        bigint juridiskPersonId PK
        string nummer
    }

    dim_fysisk_person{
        bigint fysiskPersonId PK
    }

    dim_annen_person{
        bigint fysiskPersonId PK
    }

    dim_registerenhet{
        bigint id PK
        boolean utgaatt
        bigint gaardsnummer
        bigint bruksnummer
        bigint festenummer
        bigint seksjonsnummer
        bigint zk_borettslag
        bigint andelsnummer
        bigint zk_kommuneId
    }
